<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas [
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,mayor_de_edad?,ciudad)>
<!ATTLIST persona dni CDATA #REQUIRED>
<!ATTLIST persona formapago (Contado|Tarjeta) "Contado">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mayor_de_edad EMPTY>
<!ELEMENT ciudad (#PCDATA)>
]>
<personas>
<persona dni="123123">
    <nombre>Andrea Solís</nombre>
    <mayor_de_edad />
    <ciudad>Córdoba</ciudad>
</persona>
<persona dni="234234" formapago="Tarjeta">
    <nombre>Dora la exploradora</nombre>
    <ciudad>Córdoba</ciudad>
</persona>
</personas>