<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas [
<!ELEMENT deportistas (deportista+)>
<!ELEMENT deportista (deporte,nombre)>
<!ATTLIST deporte tipo ID #REQUIRED>
<!ELEMENT deporte (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
]>
<deportistas>
<deportista>
    <deporte tipo="Atletismo"></deporte>
    <nombre>Jesse Owens</nombre>
</deportista>
<deportista>
    <deporte tipo="NataciÃ³n"></deporte> 
    <nombre>Mark Spitz</nombre>
</deportista>
</deportistas>
