<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texto [
<!ELEMENT texto (titulo,párrafo+,abreviatura,link)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT párrafo (#PCDATA)>
<!ELEMENT abreviatura (#PCDATA)>
<!ELEMENT element-name (#PCDATA)>
]>

<texto>
    <titulo>XML explicado a los niños</titulo>
    <párrafo>El <abreviatura>XML</abreviatura>define cómo crear lenguajes de marcas.</párrafo>
    <párrafo>Las marcas se añaden a un documento de texto para añadir información.</párrafo>
    <http://>www.example.org</http://>
</texto>
