=== a19sotean/a19sotean.github.io/LenguajeMarcas/vuelta_mundo/vueltamundodtd.dtd
<!ELEMENT vueltamundo (etapa)+>
<!ATTLIST vueltamundo xmlns:xsi CDATA #IMPLIED>
<!ATTLIST vueltamundo xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT etapa (descripcion, ciudad_salida, img_salida, ciudad_paso*, img_paso*, ciudad_llegada, img_llegada, transporte+)>
<!ATTLIST etapa numero CDATA #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT ciudad_salida (#PCDATA)>
<!ELEMENT img_salida (#PCDATA)>
<!ELEMENT ciudad_paso (#PCDATA)>
<!ELEMENT img_paso (#PCDATA)>
<!ELEMENT ciudad_llegada (#PCDATA)>
<!ELEMENT img_llegada (#PCDATA)>
<!ELEMENT transporte (#PCDATA)>

=== a19sotean/a19sotean.github.io/LenguajeMarcas/vuelta_mundo/vueltamundo.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="vueltamundoxsl.xsl"?>
<!DOCTYPE vueltamundo SYSTEM "vueltamundodtd.dtd">
<vueltamundo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="vueltamundoxsd.xsd">


<etapa numero="1">
    <descripcion>Phileas Fogg era todo un caballero en el Reino Unido. Él siempre iba al Reform Club. Allí jugaba al whist con sus colegas. Un día se levantó una discusión sobre poder dar la vuelta al mundo en 80 días. Los colegas decían que era imposible tal viaje en tan poco tiempo. Pero Phileas Fogg, era defensor de tal idea, y quiso apostar casi toda su fortuna a que era capaz de realizar dicho viaje. Aceptaron la apuesta y Fogg emprendió el viaje con su nuevo criado francés Passepartout.</descripcion>
    <ciudad_salida>Londres</ciudad_salida>
    <img_salida>./images/londres.jpg</img_salida>
    <ciudad_paso>París</ciudad_paso>
    <img_paso>./images/paris.jpg</img_paso>
    <ciudad_llegada>Brindisi</ciudad_llegada>
    <img_llegada>./images/brindisi.jpg</img_llegada>
    <transporte>Tren</transporte>
    <transporte>Barco</transporte>
  </etapa>

  <etapa numero="2">
    <descripcion>Apareció la primera contrariedad, porque se encontraron con el detective Fix, el cual había confundido a Fogg con un ladrón que había robado 55.000 libras en el banco de Inglaterra. Fix fue siguiendo cada paso que daban Passepartout y Phileas Fogg.</descripcion>
    <ciudad_salida>Brindisi</ciudad_salida>
    <img_salida>./images/brindisi.jpg</img_salida>
    <ciudad_llegada>Bombay</ciudad_llegada>
    <img_llegada>./images/bombay.jpg</img_llegada>
    <transporte>Barco de vapor</transporte>
  </etapa>
    
</vueltamundo>
